//
// Created by Menua on 26/05/2021.
//

#ifndef TAPROJECT2021_MENUAHOVHANNISYAN_SYSTEM_H
#define TAPROJECT2021_MENUAHOVHANNISYAN_SYSTEM_H


class system {

};


#endif //TAPROJECT2021_MENUAHOVHANNISYAN_SYSTEM_H
